/**
 * Data dummy untuk demo/portfolio mode — dipakai saat tidak ada DATABASE_URL.
 * Wisata Pangandaran: destinasi, berita, event, galeri, hotel, kuliner, rekomendasi, UKM.
 */

const now = new Date();
const lastWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

// Helper: date in past for publishedAt/createdAt
function d(daysAgo: number) {
  const d = new Date(now);
  d.setDate(d.getDate() - daysAgo);
  return d;
}

export const dummyRekomendasi = [
  {
    id: "dum-rec-1",
    judul: "Pangandaran 2 Hari 1 Malam",
    slug: "pangandaran-2-hari-1-malam",
    deskripsi:
      "Paket lengkap: Pantai Pasir Putih, Green Canyon, kuliner seafood, dan sunset di Tugu Marlin. Cocok untuk keluarga atau pasangan.",
    tema: "Keluarga",
    durasi: "2 Hari 1 Malam",
    estimasiBudget: "Rp 500rb - 1jt/orang",
    destinasiIds: ["dum-dest-1", "dum-dest-2"],
    gambarUtama:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    status: "PUBLISHED" as const,
    featured: true,
    urutan: 0,
    createdAt: d(30),
    updatedAt: d(1),
  },
  {
    id: "dum-rec-2",
    judul: "Petualangan Bahari Sehari",
    slug: "petualangan-bahari-sehari",
    deskripsi:
      "Snorkeling, kayak, dan jelajah pantai tersembunyi. Dibimbing pemandu lokal. Cocok untuk pencinta alam.",
    tema: "Petualangan",
    durasi: "1 Hari",
    estimasiBudget: "Rp 300rb - 500rb/orang",
    destinasiIds: ["dum-dest-1", "dum-dest-3"],
    gambarUtama:
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    status: "PUBLISHED" as const,
    featured: true,
    urutan: 1,
    createdAt: d(20),
    updatedAt: d(2),
  },
  {
    id: "dum-rec-3",
    judul: "Sunset & Kuliner Malam",
    slug: "sunset-kuliner-malam",
    deskripsi:
      "Nikmati golden hour di pantai, lanjut santap seafood bakar dan jalan-jalan di pasar malam.",
    tema: "Romantis",
    durasi: "1 Hari",
    estimasiBudget: "Rp 200rb - 400rb/orang",
    destinasiIds: ["dum-dest-3"],
    gambarUtama:
      "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=1200&q=80",
    status: "PUBLISHED" as const,
    featured: false,
    urutan: 2,
    createdAt: d(15),
    updatedAt: d(3),
  },
];

export const dummyHotelListing = [
  {
    id: "dum-hotel-1",
    name: "Hotel Santosa Pangandaran",
    description: "Resort tepi pantai dengan kolam renang dan restoran.",
    link: "https://example.com",
    thumbnail:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
    source: "Google Hotels",
    location: "Pangandaran",
    price: "Rp 500rb - 1jt",
    rating: 4.5,
    reviews: 320,
    propertyToken: null,
    checkInDate: null,
    checkOutDate: null,
    fetchedAt: now,
    updatedAt: now,
    createdAt: now,
  },
  {
    id: "dum-hotel-2",
    name: "Villa Sunset View",
    description: "Villa privat dengan pemandangan laut dan dapur lengkap.",
    link: "https://example.com",
    thumbnail:
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
    source: "Google Hotels",
    location: "Pangandaran",
    price: "Rp 800rb - 1,5jt",
    rating: 4.8,
    reviews: 156,
    propertyToken: null,
    checkInDate: null,
    checkOutDate: null,
    fetchedAt: now,
    updatedAt: now,
    createdAt: now,
  },
  {
    id: "dum-hotel-3",
    name: "Penginapan Nelayan",
    description: "Homestay sederhana dekat pantai, suasana lokal.",
    link: null,
    thumbnail:
      "https://images.unsplash.com/photo-1501117716987-c8e1ecb210af?auto=format&fit=crop&w=800&q=80",
    source: "Lokal",
    location: "Pangandaran",
    price: "Rp 150rb - 300rb",
    rating: 4.2,
    reviews: 89,
    propertyToken: null,
    checkInDate: null,
    checkOutDate: null,
    fetchedAt: now,
    updatedAt: now,
    createdAt: now,
  },
];

export const dummyBerita = [
  {
    id: "dum-ber-1",
    judul: "Festival Bahari Pangandaran 2025 Dibuka untuk Umum",
    slug: "festival-bahari-pangandaran-2025",
    konten: "<p>Festival tahunan kembali digelar dengan berbagai lomba dan pameran kuliner.</p>",
    ringkasan: "Festival Bahari Pangandaran 2025 resmi dibuka dengan parade dan pameran UMKM.",
    kategori: "Event",
    gambarUtama:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    tags: ["festival", "bahari", "pangandaran"],
    sourceUrl: null,
    sourceImage: null,
    isExternal: false,
    views: 1200,
    status: "PUBLISHED" as const,
    featured: true,
    publishedAt: d(2),
    expiresAt: null,
    createdAt: d(3),
    updatedAt: d(1),
    createdBy: "dum-admin",
    admin: { nama: "Admin Demo", username: "admin_berita" },
  },
  {
    id: "dum-ber-2",
    judul: "Green Canyon Kembali Buka Setelah Pemeliharaan",
    slug: "green-canyon-kembali-buka",
    konten: "<p>Objek wisata Green Canyon telah selesai pemeliharaan dan siap dikunjungi.</p>",
    ringkasan: "Green Canyon dibuka kembali dengan fasilitas yang diperbarui.",
    kategori: "Wisata",
    gambarUtama:
      "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80",
    tags: ["green-canyon", "wisata"],
    sourceUrl: null,
    sourceImage: null,
    isExternal: false,
    views: 890,
    status: "PUBLISHED" as const,
    featured: false,
    publishedAt: d(5),
    expiresAt: null,
    createdAt: d(6),
    updatedAt: d(4),
    createdBy: "dum-admin",
    admin: { nama: "Admin Demo", username: "admin_berita" },
  },
  {
    id: "dum-ber-3",
    judul: "Tips Liburan Hemat di Pangandaran",
    slug: "tips-liburan-hemat-pangandaran",
    konten: "<p>Beberapa tips menghemat budget tanpa mengurangi pengalaman liburan.</p>",
    ringkasan: "Panduan singkat liburan hemat di Pangandaran.",
    kategori: "Tips Wisata",
    gambarUtama:
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80",
    tags: ["tips", "hemat", "liburan"],
    sourceUrl: null,
    sourceImage: null,
    isExternal: false,
    views: 560,
    status: "PUBLISHED" as const,
    featured: false,
    publishedAt: d(7),
    expiresAt: null,
    createdAt: d(8),
    updatedAt: d(6),
    createdBy: "dum-admin",
    admin: { nama: "Admin Demo", username: "admin_berita" },
  },
  {
    id: "dum-ber-4",
    judul: "Kuliner Seafood Terbaik di Pangandaran",
    slug: "kuliner-seafood-terbaik-pangandaran",
    konten: "<p>Rekomendasi warung dan restoran seafood favorit warga.</p>",
    ringkasan: "Daftar kuliner seafood yang wajib dicoba.",
    kategori: "Kuliner",
    gambarUtama:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
    tags: ["kuliner", "seafood"],
    sourceUrl: null,
    sourceImage: null,
    isExternal: false,
    views: 1100,
    status: "PUBLISHED" as const,
    featured: true,
    publishedAt: d(1),
    expiresAt: null,
    createdAt: d(2),
    updatedAt: d(0),
    createdBy: "dum-admin",
    admin: { nama: "Admin Demo", username: "admin_berita" },
  },
  {
    id: "dum-ber-5",
    judul: "Sunset Terbaik di Pantai Pangandaran",
    slug: "sunset-terbaik-pantai-pangandaran",
    konten: "<p>Lokasi dan waktu terbaik untuk menikmati matahari terbenam.</p>",
    ringkasan: "Panduan spot sunset terbaik.",
    kategori: "Wisata",
    gambarUtama:
      "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=1200&q=80",
    tags: ["sunset", "pantai"],
    sourceUrl: null,
    sourceImage: null,
    isExternal: false,
    views: 780,
    status: "PUBLISHED" as const,
    featured: false,
    publishedAt: d(4),
    expiresAt: null,
    createdAt: d(5),
    updatedAt: d(3),
    createdBy: "dum-admin",
    admin: { nama: "Admin Demo", username: "admin_berita" },
  },
];

export const dummyGaleri = [
  {
    id: "dum-gal-1",
    judul: "Sunset di Pantai Pasir Putih",
    deskripsi: "Matahari terbenam dengan warna jingga memukau.",
    url: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=1200&q=80",
    thumbnail:
      "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=400&q=80",
    kategori: "SUNSET" as const,
    tags: ["sunset", "pantai", "pangandaran"],
    tipeMedia: "IMAGE" as const,
    status: "APPROVED" as const,
    featured: true,
    urutan: 0,
    createdAt: d(10),
    updatedAt: d(2),
    uploadedBy: null,
    userId: null,
    approvedBy: null,
    approvedAt: null,
  },
  {
    id: "dum-gal-2",
    judul: "Green Canyon",
    deskripsi: "Ngarai hijau dengan sungai jernih.",
    url: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80",
    thumbnail:
      "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=400&q=80",
    kategori: "PANTAI" as const,
    tags: ["green-canyon", "alam"],
    tipeMedia: "IMAGE" as const,
    status: "APPROVED" as const,
    featured: true,
    urutan: 1,
    createdAt: d(9),
    updatedAt: d(3),
    uploadedBy: null,
    userId: null,
    approvedBy: null,
    approvedAt: null,
  },
  {
    id: "dum-gal-3",
    judul: "Tugu Marlin",
    deskripsi: "Landmark ikonik Pangandaran.",
    url: "/tugu marlin.jpg",
    thumbnail: "/tugu marlin.jpg",
    kategori: "LAINNYA" as const,
    tags: ["tugu", "marlin", "landmark"],
    tipeMedia: "IMAGE" as const,
    status: "APPROVED" as const,
    featured: false,
    urutan: 2,
    createdAt: d(8),
    updatedAt: d(4),
    uploadedBy: null,
    userId: null,
    approvedBy: null,
    approvedAt: null,
  },
];

const dummyDestinasiImages = [
  { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80", caption: "Pantai Pasir Putih", isPrimary: true },
  { url: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=800&q=80", caption: "Green Canyon", isPrimary: false },
  { url: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=800&q=80", caption: "Sunset", isPrimary: false },
];

const dummyHarga = [
  { jenisHarga: "Tiket Masuk", harga: 15000 },
  { jenisHarga: "Parkir Motor", harga: 5000 },
];

export const dummyDestinasi = [
  {
    id: "dum-dest-1",
    nama: "Pantai Pasir Putih",
    slug: "pantai-pasir-putih",
    deskripsi:
      "Pantai dengan pasir putih halus dan air laut jernih. Cocok untuk bersantai, berenang, dan snorkeling. Fasilitas: toilet, warung, area parkir.",
    kategori: "PANTAI" as const,
    lokasi: "Pangandaran",
    alamat: "Jl. Pantai Pasir Putih, Pangandaran, Jawa Barat",
    koordinat: "-7.6911,108.6494",
    googleMapsUrl: "https://maps.google.com/?q=-7.6911,108.6494",
    rating: 4.8,
    jumlahReview: 1250,
    metaTitle: null,
    metaDescription: null,
    status: "PUBLISHED" as const,
    featured: true,
    urutan: 0,
    createdAt: d(60),
    updatedAt: d(5),
    createdBy: "dum-admin",
    images: [
      { id: "di1", destinasiId: "dum-dest-1", url: dummyDestinasiImages[0].url, caption: dummyDestinasiImages[0].caption, isPrimary: true, urutan: 0, createdAt: now },
      { id: "di2", destinasiId: "dum-dest-1", url: dummyDestinasiImages[1].url, caption: dummyDestinasiImages[1].caption, isPrimary: false, urutan: 1, createdAt: now },
    ],
    harga: [
      { id: "dh1", destinasiId: "dum-dest-1", jenisHarga: "Tiket Masuk", harga: 20000, keterangan: null, urutan: 0 },
      { id: "dh2", destinasiId: "dum-dest-1", jenisHarga: "Parkir Motor", harga: 5000, keterangan: null, urutan: 1 },
    ],
    fasilitas: [
      { id: "dd1", destinasiId: "dum-dest-1", jenis: "FASILITAS" as const, judul: "Toilet", konten: "Toilet umum bersih", urutan: 0 },
      { id: "dd2", destinasiId: "dum-dest-1", jenis: "FASILITAS" as const, judul: "Warung", konten: "Warung makan dan minuman", urutan: 1 },
    ],
  },
  {
    id: "dum-dest-2",
    nama: "Green Canyon",
    slug: "green-canyon",
    deskripsi:
      "Ngarai hijau dengan sungai jernih dan tebing batu. Aktivitas: perahu, berenang, foto. Wajib coba saat berkunjung Pangandaran.",
    kategori: "CAGAR_ALAM" as const,
    lokasi: "Cijulang, Pangandaran",
    alamat: "Green Canyon, Cijulang, Kab. Pangandaran",
    koordinat: "-7.7521,108.5123",
    googleMapsUrl: "https://maps.google.com/?q=-7.7521,108.5123",
    rating: 4.9,
    jumlahReview: 2100,
    metaTitle: null,
    metaDescription: null,
    status: "PUBLISHED" as const,
    featured: true,
    urutan: 1,
    createdAt: d(55),
    updatedAt: d(4),
    createdBy: "dum-admin",
    images: [
      { id: "di3", destinasiId: "dum-dest-2", url: dummyDestinasiImages[1].url, caption: "Green Canyon", isPrimary: true, urutan: 0, createdAt: now },
    ],
    harga: [
      { id: "dh3", destinasiId: "dum-dest-2", jenisHarga: "Tiket + Perahu", harga: 75000, keterangan: "Include perahu", urutan: 0 },
    ],
    fasilitas: [
      { id: "dd3", destinasiId: "dum-dest-2", jenis: "AKTIVITAS" as const, judul: "Perahu", konten: "Perahu menyusuri sungai", urutan: 0 },
    ],
  },
  {
    id: "dum-dest-3",
    nama: "Sunset Point Pangandaran",
    slug: "sunset-point",
    deskripsi:
      "Spot terbaik menikmati matahari terbenam dengan pemandangan laut. Banyak spot foto dan warung kopi.",
    kategori: "PANTAI" as const,
    lokasi: "Pangandaran",
    alamat: "Kawasan wisata Pangandaran",
    koordinat: "-7.6900,108.6500",
    googleMapsUrl: null,
    rating: 4.7,
    jumlahReview: 890,
    metaTitle: null,
    metaDescription: null,
    status: "PUBLISHED" as const,
    featured: false,
    urutan: 2,
    createdAt: d(50),
    updatedAt: d(3),
    createdBy: "dum-admin",
    images: [
      { id: "di4", destinasiId: "dum-dest-3", url: dummyDestinasiImages[2].url, caption: "Sunset", isPrimary: true, urutan: 0, createdAt: now },
    ],
    harga: dummyHarga.map((h, i) => ({ id: `dh-s${i}`, destinasiId: "dum-dest-3", ...h, keterangan: null, urutan: i })),
    fasilitas: [],
  },
];

export const dummyDestinasiForList = dummyDestinasi.map((d) => ({
  ...d,
  images: d.images.map((img) => ({ url: img.url, caption: img.caption, isPrimary: img.isPrimary })),
  harga: d.harga.map((h) => ({ jenisHarga: h.jenisHarga, harga: h.harga })),
}));

export const dummyDestinasiForRekomendasi = dummyDestinasi.map((d) => ({
  id: d.id,
  nama: d.nama,
  slug: d.slug,
  rating: d.rating,
  jumlahReview: d.jumlahReview,
  lokasi: d.lokasi,
  kategori: d.kategori,
  images: d.images.slice(0, 1).map((img) => ({ url: img.url })),
}));

export const dummyKuliner = [
  {
    id: "dum-kul-1",
    nama: "Warung Seafood Pantai",
    slug: "warung-seafood-pantai",
    deskripsi: "Seafood segar langsung dari nelayan, dibakar atau digoreng sesuai pesanan.",
    kategori: "Warung",
    lokasi: "Pangandaran",
    alamat: "Jl. Pantai, Pangandaran",
    koordinat: null,
    googleMapsUrl: null,
    hargaMin: 25000,
    hargaMax: 150000,
    nomorTelepon: null,
    jamBuka: "09:00 - 22:00",
    gambar: [
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.6,
    status: "PUBLISHED" as const,
    featured: true,
    createdAt: d(20),
    updatedAt: d(2),
  },
  {
    id: "dum-kul-2",
    nama: "Cafe Sunset",
    slug: "cafe-sunset",
    deskripsi: "Cafe dengan view laut, cocok untuk kopi dan camilan sambil menunggu sunset.",
    kategori: "Cafe",
    lokasi: "Pangandaran",
    alamat: "Kawasan wisata Pangandaran",
    koordinat: null,
    googleMapsUrl: null,
    hargaMin: 15000,
    hargaMax: 50000,
    nomorTelepon: null,
    jamBuka: "07:00 - 23:00",
    gambar: [
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    status: "PUBLISHED" as const,
    featured: false,
    createdAt: d(18),
    updatedAt: d(3),
  },
];

export const dummyEvent = [
  {
    id: "dum-ev-1",
    nama: "Festival Bahari Pangandaran 2025",
    slug: "festival-bahari-pangandaran-2025",
    deskripsi: "Festival tahunan dengan lomba perahu, pameran UMKM, dan pentas seni.",
    lokasi: "Pantai Pangandaran",
    alamat: "Kawasan pantai Pangandaran",
    koordinat: null,
    googleMapsUrl: null,
    tanggalMulai: d(30),
    tanggalSelesai: d(28),
    jamMulai: "08:00",
    jamSelesai: "22:00",
    gambar: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    thumbnail: null,
    kontakPerson: "Dinas Pariwisata",
    nomorTelepon: null,
    hargaTiket: "Gratis",
    status: "PUBLISHED" as const,
    featured: true,
    createdAt: d(60),
    updatedAt: d(5),
    createdBy: "dum-admin",
  },
];

export const dummyProfilUkm = [
  {
    id: "dum-ukm-1",
    namaUsaha: "Kerajinan Bambu Pangandaran",
    slug: "kerajinan-bambu-pangandaran",
    deskripsi: "Produk kerajinan bambu: tas, tempat tisu, hiasan. Hasil karya UMKM lokal.",
    kategori: "Kerajinan",
    pemilik: "Bapak Ahmad",
    lokasi: "Pangandaran",
    alamat: "Jl. Merdeka, Pangandaran",
    koordinat: null,
    nomorTelepon: null,
    email: null,
    instagram: null,
    facebook: null,
    whatsapp: null,
    website: null,
    logo: null,
    gambar: [],
    produkLayanan: ["Tas bambu", "Tempat tisu", "Hiasan dinding"],
    hargaRata: "Rp 50rb - 200rb",
    jamOperasional: "08:00 - 17:00",
    status: "PUBLISHED" as const,
    featured: true,
    verified: true,
    createdAt: d(40),
    updatedAt: d(4),
    createdBy: "dum-admin",
  },
];

export const dummySettings = [
  { id: "set-1", key: "site_name", value: "Wisata Pangandaran", description: null, updatedAt: now },
  { id: "set-2", key: "site_description", value: "Portal wisata dan informasi Pangandaran", description: null, updatedAt: now },
];

/** Cek apakah saat ini pakai mode dummy (tanpa database). */
export function useDummyData(): boolean {
  if (typeof process === "undefined") return false;
  return !process.env.DATABASE_URL || process.env.DATABASE_URL.trim() === "";
}
